parameters:
  core.handler.register.class: CoreBundle\Handler\RegisterHandler
services:
  core.handler.register:
    class: '%core.handler.register.class%'
    arguments:
      - '@service_container'
      - '@event_dispatcher'
