imports:
  -
    resource: TrainTypeServices.yml
  -
    resource: RecordServices.yml
  -
    resource: UserServices.yml
  -
    resource: NextTrainServices.yml
  -
    resource: NextApproachServices.yml
  -
    resource: OauthLoginServices.yml
  -
    resource: RegisterServices.yml
  -
    resource: CurrentUserServices.yml
  -
    resource: AllStatServices.yml
services: null
