facebook_login:
    path: /login/check-facebook

#google_login:
#    path: /login/check-google

custom_login:
    path: /login/check-custom

github_login:
    path: /login/check-github

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc

api_route:
    resource: "@ApiBundle/Resources/config/routing.yml"

core:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

api_login_check:
    path: /login_check
